CREATE DATABASE projectAR
GO
USE projectAR
GO
CREATE TABLE MONUMENTO(
	IDMONUMENTO INT IDENTITY PRIMARY KEY NOT NULL,
	TITLE VARCHAR(200) NOT NULL,
	URLMAPS VARCHAR(1000) NOT NULL
)
GO
CREATE TABLE DESCRIZIONE(
	IDESCRIZIONE INT IDENTITY PRIMARY KEY NOT NULL,
	DESCRIZIONE TEXT NOT NULL,
	FIELD INT NOT NULL,
	LANG VARCHAR(3) NOT NULL,
	IDMONUMENTO INT FOREIGN KEY REFERENCES MONUMENTO(IDMONUMENTO) ON DELETE CASCADE
)
GO
CREATE TABLE UTENTE(
	IDUTENTE INT IDENTITY PRIMARY KEY,
	USR VARCHAR(15) NOT NULL,
	PWD VARCHAR(150) NOT NULL
)

GO

CREATE PROC GETMONUMENTITILE(
	@ID INT
)
AS
BEGIN
	SELECT TITLE FROM MONUMENTO WHERE IDMONUMENTO = @ID
END

GO

CREATE PROC GETURL(
	@ID INT
)
AS
BEGIN
	SELECT URLMAPS FROM MONUMENTO WHERE IDMONUMENTO = @ID
END

GO

CREATE PROC GETARRAYVALORI(
	@ID INT,
	@LANG VARCHAR(3)
)
AS
BEGIN
	SELECT FIELD, DESCRIZIONE FROM DESCRIZIONE WHERE IDMONUMENTO = @ID AND LANG = @LANG
END