CREATE DATABASE PROJECTAR
GO
USE PROJECTAR
GO
CREATE TABLE MONUMENTO(
	IDMONUMENTO INT IDENTITY PRIMARY KEY NOT NULL,
	TITLE VARCHAR(200) NOT NULL
)
GO
CREATE TABLE DESCRIZIONE(
	IDESCRIZIONE INT IDENTITY PRIMARY KEY NOT NULL,
	DESCRIZIONE TEXT NOT NULL,
	FIELD INT NOT NULL,
	LANG VARCHAR(3) NOT NULL,
	IDMONUMENTO INT FOREIGN KEY REFERENCES MONUMENTO(IDMONUMENTO)
)
GO
CREATE PROC GETMONUMENTITILE(
	@ID INT
)
AS
BEGIN
	SELECT TITLE FROM MONUMENTO WHERE IDMONUMENTO = @ID
END
GO
CREATE PROC GETARRAYVALORI(
	@ID INT,
	@LANG VARCHAR(3)
)
AS
BEGIN
	SELECT DESCRIZIONE, FIELD FROM DESCRIZIONE WHERE IDMONUMENTO = @ID AND LANG = @LANG
END